In [1]:
import numpy as np

In [2]:
path = "data_set/datingTestSet.txt"

In [3]:
X=[]
y=[]
with open(path,'r') as f:
    readlines_ = f.readlines()
    for line in readlines_:
        line_split = line.strip('\n').split('\t')
        X.append([np.float32(line_split[0]),np.float32(line_split[1]),np.float32(line_split[2])])
        y.append(line_split[-1])

In [4]:
X=np.array(X)
y=np.array(y)

In [5]:
X = (X-np.min(X,axis = 0))/(np.max(X,axis = 0) - np.min(X,axis = 0))
X

array([[0.44832537, 0.39805138, 0.5623336 ],
       [0.1587326 , 0.34195465, 0.9872441 ],
       [0.28542942, 0.06892523, 0.4744963 ],
       ...,
       [0.29115948, 0.5091029 , 0.51079494],
       [0.527111  , 0.4366545 , 0.42900482],
       [0.47940794, 0.37680906, 0.7857181 ]], dtype=float32)

In [6]:
random_X_indec = np.random.permutation(1000)

In [7]:
X[random_X_indec]
y[random_X_indec]

array(['largeDoses', 'largeDoses', 'smallDoses', 'smallDoses',
       'didntLike', 'smallDoses', 'largeDoses', 'smallDoses', 'didntLike',
       'smallDoses', 'didntLike', 'didntLike', 'didntLike', 'smallDoses',
       'smallDoses', 'smallDoses', 'smallDoses', 'smallDoses',
       'largeDoses', 'largeDoses', 'smallDoses', 'smallDoses',
       'smallDoses', 'didntLike', 'smallDoses', 'largeDoses', 'didntLike',
       'smallDoses', 'didntLike', 'smallDoses', 'largeDoses',
       'largeDoses', 'largeDoses', 'smallDoses', 'smallDoses',
       'largeDoses', 'largeDoses', 'largeDoses', 'smallDoses',
       'largeDoses', 'largeDoses', 'smallDoses', 'didntLike',
       'smallDoses', 'smallDoses', 'largeDoses', 'smallDoses',
       'largeDoses', 'smallDoses', 'smallDoses', 'largeDoses',
       'smallDoses', 'smallDoses', 'didntLike', 'smallDoses',
       'largeDoses', 'smallDoses', 'didntLike', 'didntLike', 'smallDoses',
       'largeDoses', 'largeDoses', 'smallDoses', 'smallDoses',
       'did

In [8]:
test_X = X[random_X_indec][:200]
test_y = y[random_X_indec][:200]

In [9]:
train_X= X[random_X_indec][200:]
train_y = y[random_X_indec][200:]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [12]:
X_train.shape

(800, 3)

In [13]:
y_train.shape

(800,)

In [14]:
D = np.sum((X_train - X_test[0])**2,axis = 1)**0.5
D

array([0.5009853 , 0.67279243, 0.28272453, 0.46856233, 0.58655715,
       0.39310014, 0.69152045, 0.75956815, 0.4271073 , 0.5588441 ,
       0.5699323 , 0.42629477, 0.6930947 , 0.23593444, 0.4603325 ,
       0.6537342 , 0.5233861 , 0.52461344, 0.6141777 , 0.4380009 ,
       0.5629949 , 0.8370085 , 0.4225926 , 0.5882023 , 0.6506874 ,
       0.56228626, 0.7337634 , 0.5968487 , 0.6913893 , 0.4986038 ,
       0.71039236, 0.7047584 , 0.44466203, 0.6166786 , 0.6576316 ,
       0.51050556, 0.5188421 , 0.8039183 , 0.31432244, 0.49291965,
       0.5309116 , 0.03799123, 0.62584287, 0.77650505, 0.5045126 ,
       0.8754828 , 0.6159795 , 0.6895083 , 0.41721296, 0.4482113 ,
       0.31855208, 0.7402264 , 0.5075168 , 0.7060249 , 0.6901071 ,
       0.3314686 , 0.45498756, 0.3259202 , 0.20322882, 0.24819474,
       0.26658872, 0.6565523 , 0.8015435 , 0.41833514, 0.424524  ,
       0.738076  , 0.70853305, 0.6750381 , 0.4506804 , 0.90368474,
       0.4737618 , 0.4223    , 0.55024344, 0.6616583 , 0.31035

In [15]:
sort_D = np.argsort(D)[:7]
sort_D

array([ 41, 589, 507, 336, 133, 295, 446], dtype=int64)

In [16]:
train_y[sort_D]

array(['smallDoses', 'largeDoses', 'smallDoses', 'smallDoses',
       'smallDoses', 'smallDoses', 'largeDoses'], dtype='<U10')

In [17]:
test_y[0]

'largeDoses'

In [18]:
aaa = train_y[sort_D]
aaa

array(['smallDoses', 'largeDoses', 'smallDoses', 'smallDoses',
       'smallDoses', 'smallDoses', 'largeDoses'], dtype='<U10')

In [19]:
bbb = {}

In [20]:
for i in aaa:
    if i not in bbb.keys():
        bbb[i] = 1
    else:
        bbb[i] += 1
bbb

{'largeDoses': 2, 'smallDoses': 5}

In [21]:
ccc = 0
predict_y = []
for key,value in bbb.items():
    if value > ccc:
        ccc = value
        predict_y.append(key)
print(predict_y[-1])

smallDoses


In [22]:
def KNN(X,y,test_X,test_y,K):

    PREDICT_y = []
    for i in range(test_X.shape[0]):
        D = np.sum((X - test_X[i])**2,axis = 1)**0.5
        sort_D = np.argsort(D)[:K]
        aaa = y[sort_D]
        
        bbb = {}
        for i in aaa:
            if i not in bbb.keys():
                bbb[i] = 1
            else:
                bbb[i] += 1
                
        ccc = 0
        predict_y = []
        for key,value in bbb.items():
            if value > ccc:
                ccc = value
                predict_y.append(key)
        PREDICT_y.append(predict_y[-1])
        
    PREDICT_y = np.array(PREDICT_y)
    
    ######### accuracy ########
    accuracy = np.sum(PREDICT_y == test_y) / test_X.shape[0]
    print(accuracy)

In [23]:
KNN(train_X,train_y,test_X,test_y,5)

0.94


In [24]:
def loadData(path):
    """
    load data
    
    Return:
    ------
        1.Train_data is numpy.
        2.labels; as same as numpy.
    """
    Train_data = []
    labels = []
    np.random.shuffle
    
    with open(path) as f:
        
        original_data = f.readlines()
        
    for data in original_data:
        data_split = data.strip().split('\t')
        train_ = data_split[:-1]
        label_ = data_split[-1]
        Train_data.append(train_)
        labels.append(label_)
    
    
    return np.array(Train_data,dtype='float'),np.array(labels)

In [25]:
path = "data_set/datingTestSet.txt"

X,y = loadData(path=path)

In [26]:
X.shape

(1000, 3)

In [27]:
y.shape

(1000,)

In [28]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

print(clf.predict(X_test))
score = clf.score(X_test,y_test)
print(score)

['largeDoses' 'smallDoses' 'smallDoses' 'didntLike' 'smallDoses'
 'didntLike' 'largeDoses' 'largeDoses' 'didntLike' 'largeDoses'
 'smallDoses' 'didntLike' 'didntLike' 'didntLike' 'didntLike' 'largeDoses'
 'largeDoses' 'largeDoses' 'largeDoses' 'didntLike' 'largeDoses'
 'didntLike' 'smallDoses' 'smallDoses' 'didntLike' 'didntLike'
 'largeDoses' 'smallDoses' 'didntLike' 'didntLike' 'smallDoses'
 'largeDoses' 'smallDoses' 'smallDoses' 'didntLike' 'largeDoses'
 'smallDoses' 'largeDoses' 'smallDoses' 'smallDoses' 'didntLike'
 'largeDoses' 'largeDoses' 'smallDoses' 'smallDoses' 'didntLike'
 'largeDoses' 'didntLike' 'largeDoses' 'didntLike' 'largeDoses'
 'smallDoses' 'didntLike' 'didntLike' 'largeDoses' 'largeDoses'
 'didntLike' 'didntLike' 'didntLike' 'smallDoses' 'largeDoses'
 'smallDoses' 'largeDoses' 'didntLike' 'smallDoses' 'didntLike'
 'smallDoses' 'largeDoses' 'smallDoses' 'didntLike' 'largeDoses'
 'largeDoses' 'largeDoses' 'largeDoses' 'largeDoses' 'didntLike'
 'smallDoses' 'largeDose