In [3]:
import numpy as np

In [4]:
def loadDataSet():
    """
    Create dataset
    
    Returns:
        posting list and classVec
    """
    postingList = [['my','dog','has','flea','problems','help','please'],
                  ['maybe','not','take','him','to','dog','park','stupid'],
                  ['my','dalmation','is','so','cute','I','love','him'],
                  ['stop','posting','stupid','worthless','grabage'],
                  ['mr','licks','ate','my','steak','how','to','stop','him'],
                  ['quit','buying','worthless','dog','food','stupid']]
    classVec = np.array([0,1,0,1,0,1]) # 1 is absive,0 not
    
    return postingList,classVec

In [5]:
postingList,classVec = loadDataSet()

In [6]:
postingList

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'grabage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [9]:
def set_vocabulary(postingList):
    #整体去重（set/unique/for循环）
    vocabulary = set([])
    for m in postingList:
        vocabulary = vocabulary | set(m)
        
    return list(vocabulary)    #词集
    

In [14]:
vocabulary = set_vocabulary(postingList)
vocabulary

['love',
 'licks',
 'dog',
 'mr',
 'take',
 'quit',
 'buying',
 'problems',
 'grabage',
 'stupid',
 'is',
 'cute',
 'has',
 'so',
 'park',
 'him',
 'stop',
 'steak',
 'I',
 'please',
 'help',
 'not',
 'posting',
 'food',
 'dalmation',
 'maybe',
 'worthless',
 'ate',
 'how',
 'to',
 'my',
 'flea']

In [33]:
def word2vec(vocabulary,postingList):
    m,n = len(postingList),len(vocabulary)
    word_Vec = np.zeros((m,n))
    
    for i in range(m):
        for word in postingList[i]:
            index = vocabulary.index(word)
            word_Vec[i,index] = 1
        return(word_Vec)

In [34]:
words_Vec = word2vec(vocabulary,postingList)
words_Vec

array([[0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
words_Vec.shape

(6, 32)

In [84]:
test_x = [['my','maybe','stupid'],['cute','is'],['quit','buying','worthless']]
test_y = [1,0,0]
test_x = word2vec(vocabulary,test_x)
test_x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [89]:
#def Model(y):
    #先求先验概率
    #条件概率（拆分样本集）
    #for label in unique_y:
        

In [88]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()  #初始化
clf.fit(words_Vec, classVec)  #训练

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
print(clf.predict(test_x))  #预测
#评分
score = clf.score(test_x,test_y)
print(score)

[0 0 0]
0.6666666666666666


In [87]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

def create_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['label'] = iris.target
    df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
    data = np.array(df.iloc[:100, [0, 1, -1]])
    return data[:,:2], data[:,-1]

X, y = create_data()

In [61]:
X.shape

(100, 2)

In [63]:
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)
print(X_train)

[[6.8 2.8]
 [4.3 3. ]
 [5.8 2.7]
 [5.8 2.7]
 [6.  3.4]
 [4.8 3.1]
 [5.5 2.5]
 [6.4 2.9]
 [5.  3.5]
 [5.4 3.4]
 [5.  3.6]
 [6.3 2.3]
 [5.1 3.5]
 [6.3 3.3]
 [5.1 3.7]
 [5.6 3. ]
 [5.8 4. ]
 [4.6 3.4]
 [5.5 2.6]
 [6.  2.7]
 [6.1 3. ]
 [5.3 3.7]
 [6.  2.2]
 [5.1 3.5]
 [6.2 2.9]
 [5.  2. ]
 [5.2 3.4]
 [5.7 4.4]
 [4.8 3. ]
 [5.9 3.2]
 [5.  2.3]
 [4.8 3. ]
 [4.8 3.4]
 [5.2 3.5]
 [5.5 2.4]
 [5.  3.4]
 [5.7 2.8]
 [4.7 3.2]
 [4.8 3.4]
 [6.6 3. ]
 [5.  3. ]
 [6.3 2.5]
 [5.1 3.3]
 [5.7 2.9]
 [5.6 2.5]
 [5.  3.2]
 [6.7 3. ]
 [5.9 3. ]
 [4.6 3.6]
 [4.4 3. ]
 [6.2 2.2]
 [5.1 2.5]
 [6.6 2.9]
 [5.  3.4]
 [5.  3.5]
 [5.6 3. ]
 [5.1 3.8]
 [5.5 4.2]
 [4.9 3.1]
 [5.4 3.9]
 [6.  2.9]
 [5.5 2.3]
 [4.5 2.3]
 [6.1 2.9]
 [4.9 2.4]
 [4.6 3.2]
 [6.7 3.1]
 [5.6 2.7]
 [5.4 3.9]
 [4.9 3.1]
 [5.4 3.4]
 [4.9 3.1]
 [5.4 3.7]
 [6.7 3.1]
 [4.7 3.2]
 [4.9 3. ]
 [5.6 2.9]
 [5.  3.3]
 [7.  3.2]
 [5.7 2.6]]


In [77]:
X_train.shape

(80, 2)

In [78]:
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [81]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()  #初始化
clf.fit(X_train, y_train)  #训练

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
print(clf.predict(X_test)) 

score = clf.score(X_test,y_test)
print(score)

[1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
0.95


In [83]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

print(clf.predict(X_test))
score = clf.score(X_test,y_test)
print(score)

[1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
1.0
